improveo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import PostCreateView, like_post, GeneralDetailPost, ProblemDetailPost, GeneralPostDelete

app_name = 'posts'

urlpatterns = [
    path('', PostCreateView.as_view(), name="post-list"),
    path('like/', like_post, name="post-like"),
    path('<pk>/detail/', GeneralDetailPost.as_view(), name='gp-detail'),
    path('<pk1>/<pk>/detail/', ProblemDetailPost.as_view(), name="pp-detail"),
    path('<pk>/delete/', GeneralPostDelete.as_view(), name="gp-delete"),
]

profiles/urls.py
from django.urls import path
from django.conf.urls import url
from .views import profile_view
from . import views
app_name = 'profiles'

urlpatterns = [
    path('', profile_view, name='profile-view'),
    path('panel/', views.panel, name='panel'),
    path('prices/', views.prices, name='prices'),
    path('stock/', views.stock, name='stock'),
    # path('sleep/', test_view_1, name='test-view-1'),
    # path('view3/', test_view_2, name='test-view-2'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
import uuid
import os
# Create your models here.


def get_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "{}.{}".format(uuid.uuid4(), ext)
    return os.path.join('uploads/profile/img', filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_picture = models.ImageField(upload_to=get_upload_path, default='uploads/profile/img/avatar.png', validators=[
        FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    website = models.CharField(max_length=220)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.user)

profiles/forms.py
from .models import Profile
from django import forms


class ProfileModelForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': 'Few words about you...',
            'rows': 3,
        }
    ))

    website = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'placeholder': 'your website'
        }
    ))

    class Meta:
        model = Profile
        fields = ('bio', 'website', 'profile_picture')

profiles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Profile
from .forms import ProfileModelForm
from . import views


def stock(request):
    import requests
    import json
    api_request = requests.get("https://cloud.iexapis.com/stable/stock/aapl/quote?token=pk_2462f6f6db344a55b0a7cdc46b090cef")

    try:
        dolla = json.loads(api_request.content)


    except Exception as e:

        dolla = "Error..."


    return render(request, 'profiles/stock.html', {'dolla':dolla})


def panel(request):
    
    import requests
    import json
    #price data
    api_data = requests.get("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,XRP,ETC,DOGE,LTC&tsyms=USD")
    data = json.loads(api_data.content)
    api_request = requests.get(
            "https://min-api.cryptocompare.com/data/v2/news/?lang=EN")
    api = json.loads(api_request.content)
    
    return render(request, 'profiles/home.html', { 'api':api, 'data':data})
# Create your views here.


def prices(request):
    if request.method == 'POST':
        import requests
        import json
        quote = request.POST['quote']
        quote = quote.upper()
        quote_request = requests.get("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=" + quote + "&tsyms=USD")
        crypto = json.loads(quote_request.content)        
        return render(request, 'profiles/prices.html', {'quote':quote,'crypto': crypto})

    else:
        notfound = "Enter a crypto symbol"
        return render(request, 'profiles/prices.html', {'notfound':notfound})


def profile_view(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None

    form = ProfileModelForm(request.POST or None,
                            request.FILES or None, instance=profile)

    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.bio = form.cleaned_data.get('bio')
            instance.website = form.cleaned_data.get('website')
            instance.profile_picture = form.cleaned_data.get('profile_picture')
            form.save()

    context = {
        'object': profile,
        'form': form
    }

    return render(request, 'profiles/profile.html', context)

# def test_view(request):
#     hw = "Hello World"
#     return HttpResponse(hw)


# def test_view_1(request):
#     gs = "go to sleep"
#     return HttpResponse(gs)


# def test_view_2(request):
#     if request.user.is_authenticated:
#         user = request.user
#         profile = Profile.objects.get(user=user)
#     else:
#         profile = 'no profile'

#     context = {
#         'user': profile
#     }

#     return render(request, 'profiles/test.html', context)

profiles/templates/profiles/home.html
{% load static %}
{% load pic_name %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Admin Panel</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{%static 'back/admin/plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- IonIcons -->
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'back/admin/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>

    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" method="POST" action="{% url 'profiles:prices' %}">
    {% csrf_token %}
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="crypto💲" aria-label="Search" name="quote">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>



    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ object.profile_picture.url }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Tye
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{%static 'back/admin/dist/img/avatar.png'%}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{%static 'back/admin/dist/img/user.png' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    
      <img src="{{ picture.url }}" class="img-avatar brand-image img-circle" alt="profile picture">
      
    
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
        
        </div>
        <div class="info">
          <a class="d-block">Beallie 🐐</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
      <h2 style="color: #fff">Site Settings</h2>
          <ul class="nav nav-treeview">

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>

            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i> 
            </a>

          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-money"></i>
 
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
            </a>
          </li>
          </li>
            <li class="nav-item has-treeview">
            <a href="pages/calendar.html" class="nav-link">
              <i class="nav-icon fas fa-calendar-alt"></i>
              <p>
                Calendar
                <span class="badge badge-info right">2</span>
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book"></i>
              <p>
                Invoices
              </p>
            </a>
            </li>
            </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">


{% block content %}

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">High</th>
      <th scope="col">Low</th>
      <th scope="col">Market Cap</th>
    </tr>
  </thead>
   <tbody>
   {% for key,value in data.DISPLAY.items %}
 
 
    <tr>
      <td>{{ key }}</td>
      <td>{{ value.USD.PRICE }}</td>
      <td>{{ value.USD.HIGHDAY }}</td>
      <td>{{ value.USD.LOWDAY}}</td>
      <td>{{ value.USD.MKTCAP}}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

  <div class="container">                                                           
<div class="row">
                 
                  {% for x in api.Data %}

               <div class="col-sm">
                  <div class="card-deck">
                   

                  <div class="card" style="width: 18rem;">
                
                    <img class="card-img-top" src="{{ x.imageurl }}" alt="{{ x.source }}">
                    <div class="card-body">
                      <h5 class="card-title">{{ x.title }}</h5>
                      <p class="card-text">{{ x.body }}</p>
                      <a href="{{ x.url}}" class="btn btn-primary">Learn more</a>
                    </div>
                 
                  </div>
                  </div>
                  <br />
                  </div>

                  {% endfor %}
                  </div>
            </div>
      
{% endblock %}
    </span>




        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.4
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{%static 'back/admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{%static 'back/admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE -->
<script src="{%static 'back/admin/dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{%static 'back/admin/plugins/chart.js/Chart.min.js' %}"></script>
<script src="{%static 'back/admin/dist/js/demo.js' %}"></script>
<script src="{%static 'back/admin/dist/js/pages/dashboard3.js' %}"></script>
</body>
</html>

profiles/templates/profiles/prices.html
{% extends 'profiles/home.html' %}

{% block content %}





{% if crypto.Response %}
{{ quote }} doesn't exist. Try a crypto symbol like btc or xrp
{% endif %}

   {% for key,value in crypto.DISPLAY.items %}
 
 <div class="media">
   <img class="align-self-center mr-3" src={{ value.USD.IMAGEURL }} alt="{{ value.USD.source }}">
  <div class="media-body">
    <h5 class="mt-2">{{ key }}</h5>
   
    <p> <strong>Current Price: </strong>{{ value.USD.PRICE }}</p>
    <p class="mb-0"><strong>Daily High:</strong> {{ value.USD.HIGHDAY }}<br/>
          <strong>Daily Low:</strong>{{ value.USD.LOWDAY}}<br/>
      <strong>Market Cap:</strong>{{ value.USD.MKTCAP}}<br/>
    </p>
  </div>
</div>
        

{% endfor %}

<br/>

{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}
{% load pic_name %}
{% load crispy_forms_tags %}

<!--
{% block title %} <a href="/">Home</a> {% endblock title %}
-->
{% block content %}



<div class="col-9 mx-auto mt-2">
<div class="card p-4">

<div class="h4">Edit Profile</div>

    <div class="img-thumbnail mx-auto">
        <img src="{{ object.profile_picture.url }}" width="200" height="200">  
    </div>
    <div><span class="font-weight-bold">Username: </span> {{ object.user.username }}</div>
    <div><span class="font-weight-bold">Email: </span> {{ object.user.email }} </div>
    <div><span class="font-weight-bold">Bio: </span> {{ object.bio }}</div>
    <div><span class="font-weight-bold">Website: </span>{{ object.website }}</div>
    <div><span class="font-weight-bold">Joined: </span>{{ object.created|date }}</div>
    <br>
    <div>
        <span class="font-weight-bold">Current picture: </span>{{ object.profile_picture.url|pic_name }}
    </div>
  
  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary mt-5" data-toggle="modal" data-target="#exampleModal">
  Update profile
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

      </div>
      <div class="modal-footer">
       <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" type="submit">Save changes</button>
        </form> 
      </div>
    </div>
  </div>
</div>

</div>    
</div>
</div>
</div>

{% endblock %}

profiles/templates/profiles/profile_.html
{% extends 'base.html' %}
{% load pic_name %}
{% load crispy_forms_tags %}
{% block title %} profile {% endblock title %}

{% block content %}

<div class="col-9 mx-auto">
<div class="card p-4">

<div class="h4">Edit Profile</div>

    <div class="img-thumbnail mx-auto">
        <img src="" width="200" height="200">  
    </div>
    <div><span class="font-weight-bold">Username: </span></div>
    <div><span class="font-weight-bold">Email: </span></div>
    <div><span class="font-weight-bold">Bio: </span> </div>
    <div><span class="font-weight-bold">Website: </span></div>
    <div><span class="font-weight-bold">Joined: </span></div>
    <br>
    <div>
        <span class="font-weight-bold">Current picture: </span>
    </div>
  
  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary mt-5" data-toggle="modal" data-target="#exampleModal">
  Update profile
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

      </div>
      <div class="modal-footer">
       <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" type="submit">Save changes</button>
        </form> 
      </div>
    </div>
  </div>
</div>

</div>    
</div>
</div>
</div>

{% endblock content %}

profiles/templates/profiles/stock.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Admin Panel</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{%static 'back/admin/plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- IonIcons -->
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'back/admin/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">


<div>

<h1>{{ user }}</h1>
<br />

{{ dolla }}

</div>


</body>
</html>

profiles/templates/profiles/test.html
{% extends 'base.html' %}

{% block title %} view3 {% endblock title %}

{% block content %}

<h1>{{ user }}</h1>
<br>
<a href="{% url 'profiles:test-view' %}"><button class="btn btn-primary">Hello world</button></a>
<a href="{% url 'profiles:test-view-1' %}"><button class="btn btn-primary">go to sleep</button></a>
{% endblock content %}