improveo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import PostCreateView, like_post, GeneralDetailPost, ProblemDetailPost, GeneralPostDelete

app_name = 'posts'

urlpatterns = [
    path('', PostCreateView.as_view(), name="post-list"),
    path('like/', like_post, name="post-like"),
    path('<pk>/detail/', GeneralDetailPost.as_view(), name='gp-detail'),
    path('<pk1>/<pk>/detail/', ProblemDetailPost.as_view(), name="pp-detail"),
    path('<pk>/delete/', GeneralPostDelete.as_view(), name="gp-delete"),
]

reports/urls.py
from django.urls import path
from .views import (
    report_view, delete_view, ReportUpdateView, HomeView, SelectView, main_report_summary, get_generated_problems_in_pdf
)

app_name = 'reports'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('reports/', SelectView.as_view(), name="select-view"),
    path('reports/summary/', main_report_summary, name="summary-view"),
    path('reports/<str:production_line>/<pk>/update/',
         ReportUpdateView.as_view(), name="update-view"),
    path('reports/<str:production_line>/', report_view, name="report-view"),
    path('reports/delete/<pk>/', delete_view, name='delete-view'),
    path('reports/generate/pdf/', get_generated_problems_in_pdf, name='pdf'),
]

# /{{obj.production_line}}/{{obj.pk}}/update/

reports/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from products.models import Product
from categories.models import Category
from areas.models import ProductionLine
from django.urls import reverse
from django.db.models import Sum, Avg
import random
from datetime import datetime
# Create your models here.

# hours= (
#     ("1", "1"),
#     ("2", "2"),
#     ("3", "3"),
#     ...
# )

hours = ([(str(x), str(x)) for x in range(1, 25)])

el = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
      'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

'''
get_queryset() - method responsible for retrieving all the data from the database according to
               the defined querysets
super()        -  method which returns a proxy object that allows you to refer parent class

def get_all_active(self):
    return super().get_queryset().filter(draft=False)
    return Post.objects.filter(draft=False)
'''


class ReportQueryset(models.QuerySet):
    def get_by_line_and_day(self, day, line_id):
        return self.filter(day=day, production_line__id=line_id)

    def aggregate_execution(self):
        return self.aggregate(Sum('execution'))

    def aggregate_plan(self):
        return self.aggregate(Sum('plan'))


class ReportManager(models.Manager):
    def get_queryset(self):
        return ReportQueryset(self.model, using=self._db)

    def get_by_line_and_day(self, day, line_id):
        return self.get_queryset().get_by_line_and_day(day, line_id)

    def aggregate_execution(self):
        return self.get_queryset().aggregate_execution()

    def aggregate_plan(self):
        return self.get_queryset().aggregate_plan()


class Report(models.Model):
    day = models.DateField(default=timezone.now)
    start_hour = models.CharField(max_length=2, choices=hours)
    end_hour = models.CharField(max_length=2, choices=hours)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    plan = models.PositiveIntegerField()
    execution = models.PositiveIntegerField()
    production_line = models.ForeignKey(
        ProductionLine, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ReportManager()

    def get_day(self):
        return self.day.strftime('%Y/%m/%d')

    def get_absolute_url(self):
        return reverse("reports:update-view", kwargs={'production_line': self.production_line, 'pk': self.pk, })

    def __str__(self):
        return "{}-{}-{}".format(self.start_hour, self.end_hour, self.production_line)

    class Meta:
        ordering = ('-created',)


def random_code():
    random.shuffle(el)
    code = [str(x) for x in el[:12]]
    str_code = ''.join(code)

    return str_code


class ProblemReportedManager(models.Manager):

    def get_problems_by_day_and_line(self, day, line):
        return super().get_queryset().filter(report__day=day, report__production_line__name=line)

    def problems_from_today(self):
        now = datetime.now().strftime('%Y-%m-%d')
        return super().get_queryset().filter(report__day=now)


class ProblemReported(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    problem_id = models.CharField(
        max_length=12, unique=True, blank=True, default=random_code)
    breakdown = models.PositiveIntegerField()
    public = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProblemReportedManager()

    def __str__(self):
        return "{}-{}".format(self.category.name, self.description[:20])

    class Meta:
        verbose_name = "Problem Reported"
        verbose_name_plural = "Problems Reported"

reports/forms.py
from django import forms
from .models import Report, ProblemReported
from django.shortcuts import get_object_or_404
from areas.models import ProductionLine


class ReportResultForm(forms.Form):
    production_line = forms.ModelChoiceField(
        queryset=ProductionLine.objects.all())
    day = forms.CharField(widget=forms.DateTimeInput(
        attrs={'class': 'datepicker'}
    ))


class ReportSelectLineForm(forms.Form):
    production_line = forms.ModelChoiceField(
        queryset=ProductionLine.objects.none(), label='')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        # print(user)
        super(ReportSelectLineForm, self).__init__(*args, **kwargs)
        self.fields['production_line'].queryset = ProductionLine.objects.filter(
            team_leader__user__username=user)


class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        # fields = '__all__'
        exclude = ('user', 'production_line',)

    def __init__(self, *args, **kwargs):
        production_line = kwargs.pop('production_line', None)
        super().__init__(*args, **kwargs)
        if production_line is not None:
            line = get_object_or_404(ProductionLine, name=production_line)
            # print(line.name)
            self.fields['product'].queryset = line.products.all()


class ProblemReportedForm(forms.ModelForm):

    class Meta:
        model = ProblemReported
        # fields = '__all__'
        exclude = ('user', 'report', 'problem_id')

reports/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ReportForm, ProblemReportedForm, ReportSelectLineForm, ReportResultForm
from .models import Report, ProblemReported
from areas.models import ProductionLine
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, FormView
from django.urls import reverse_lazy

from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


@login_required
def get_generated_problems_in_pdf(request):

    # queryset
    problems = ProblemReported.objects.problems_from_today()

    # context passed in the template
    context = {'problems': problems}

    # render
    html_string = render_to_string(
        'reports/problems.html', context)
    # html = HTML(string=html_string)
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    result = html.write_pdf()

    # http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=problem_list.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response


@login_required
def main_report_summary(request):
    try:
        day = request.session.get('day', None)
        prod_id = request.session.get('production_line', None)
        production_line = ProductionLine.objects.get(id=prod_id)
        execution = Report.objects.get_by_line_and_day(
            day, prod_id).aggregate_execution()['execution__sum']
        plan = Report.objects.get_by_line_and_day(
            day, prod_id).aggregate_plan()['plan__sum']
        problems = ProblemReported.objects.get_problems_by_day_and_line(
            day, production_line)
    except:
        return redirect('reports:select-view')

    context = {
        'execution': execution,
        'plan': plan,
        'problems_reported': problems,
        'day': day,
        'line': production_line,
    }

    del request.session['day']
    del request.session['production_line']

    return render(request, 'reports/summary.html', context)


class SelectView(LoginRequiredMixin, FormView):
    template_name = 'reports/select.html'
    form_class = ReportResultForm
    success_url = reverse_lazy('reports:summary-view')

    def form_valid(self, form):
        self.request.session['day'] = self.request.POST.get('day', None)
        self.request.session['production_line'] = self.request.POST.get(
            'production_line', None)
        print(self.request.session['day'])
        return super(SelectView, self).form_valid(form)


class HomeView(FormView):
    template_name = 'reports/home.html'
    form_class = ReportSelectLineForm

    def get_form_kwargs(self):
        kwargs = super(HomeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, *args, **kwargs):
        prod_line = self.request.POST.get("prod_line")
        return redirect('reports:report-view', production_line=prod_line)


class ReportUpdateView(LoginRequiredMixin, UpdateView):
    model = Report
    form_class = ReportForm
    template_name = 'reports/update.html'

    def get_success_url(self):
        return self.request.path


@login_required
def delete_view(request, *args, **kwargs):
    r_id = kwargs.get("pk")
    obj = Report.objects.get(id=r_id)
    obj.delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def report_view(request, production_line):
    form = ReportForm(request.POST or None, production_line=production_line)
    pform = ProblemReportedForm(request.POST or None)
    queryset = Report.objects.filter(production_line__name=production_line)
    line = get_object_or_404(ProductionLine, name=production_line)

    if 'submitbtn1' in request.POST:
        r_id = request.POST.get("report_id")
        print(r_id)

        if pform.is_valid():
            report = Report.objects.get(id=r_id)
            print("data here")
            obj = pform.save(commit=False)
            obj.user = request.user
            obj.report = report
            obj.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))

    elif 'submitbtn2' in request.POST:
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.production_line = line
            obj.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))

    context = {
        'form': form,
        'pform': pform,
        'object_list': queryset,
    }

    return render(request, 'reports/report.html', context)

reports/templates/reports/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} home {% endblock title %}

{% block content %}


   <!-- <div class="text-center text-white h1 mb-5">Welcome to MutationCode</div> -->






						



        {% if request.user.is_authenticated %}
 <h1 style="text-align:center; color:#fff">Welcome Back!</h1>
        {% else %}
            <div class="text-white text-center h3"><a href="{% url 'account_login' %}" style="text-decoration: none">Login for more!</a></div>


{% endif %}

<script>
$('#div_id_production_line').on("change", function() {
    const pl = $('#id_production_line option:selected').text()
    console.log(pl)
    $('#prod_line').val(pl) 
});

</script>












{% endblock content %}

reports/templates/reports/problems.html
{% load static %}
<html>
<head>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-ve35{border-color:#c0c0c0;text-align:left;vertical-align:middle}
.tg .tg-wo29{border-color:#c0c0c0;text-align:left;vertical-align:top}
</style>
</head>

<h3> Problems </h3>

{% for p in problems  %}
<p> {{ p.created }} </p>


<table class="tg">
  <tr>
    <th class="tg-ve35">category</th>
    <th class="tg-wo29">{{ p.category }}</th>
  </tr>
  <tr>
    <td class="tg-wo29">description</td>
    <td class="tg-wo29">{{ p.description }}</td>
  </tr>
  <tr>
    <td class="tg-wo29">id</td>
    <td class="tg-wo29">{{ p.problem_id}}</td>
  </tr>
  <tr>
    <td class="tg-wo29">breakdown</td>
    <td class="tg-wo29">{{ p.breakdown}} min</td>
  </tr>
</table>
</div>

{% endfor %}

  </div>
</div>
</html>

reports/templates/reports/report.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} report {% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="problemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Report problems</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            {{pform|crispy}}
            <input type="hidden" name="report_id" id="report_id">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" name="submitbtn1" class="btn btn-primary">Send</button>
        </div>
       </form> 
    </div>
  </div>
</div>

<div class="container bg-white shadow-lg rounded py-2">
    <div class="row">
        <div class="col-2">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy}}
                <button type="submit" name="submitbtn2" class="btn btn-primary w-100 shadow-sm mt-3"><i class="far fa-paper-plane pr-3"></i>Send</button>
            </form>
        </div>
        <div class="col-10">
            <div style="overflow-y:scroll; height:85vh" class="w-100 bg-light rounded border">
                <table class="table">
                    <thead class="thead-light">
                        <tr class="text-center">
                            <th scope="col">Day</th>
                            <th scope="col">Start</th>
                            <th scope="col">End</th>
                            <th scope="col">Product</th>
                            <th scope="col">Plan</th>
                            <th scope="col">Execution</th>
                            <th scope="col">Line</th>
                            <th scope="col"></th>
                            <th scope="col">Problems</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                            <tr class="text-center">
                                <td>{{obj.get_day}}</td>
                                <td>{{obj.start_hour}}</td>
                                <td>{{obj.end_hour}}</td>
                                <td>{{obj.product}}</td>
                                <td>{{obj.plan}}</td>
                                <td>{{obj.execution}}</td>
                                <td>{{obj.production_line}}</td>
                                <td>
                                    {% if obj.problemreported_set.all %}
                                        <div class="badge badge-danger">P</div>
                                    {% endif %}
                                </td>

                                <td class="fit">
                                    <button class="btn btn-warning open-modal" data-toggle="modal" data-target="#problemModal" data-url={{obj.id}}><i class="fas fa-exclamation-triangle"></i></button>
                                </td>
                                <td class="fit">
                                    <a href="{{obj.get_absolute_url}}"><button class="btn btn-info"><i class="far fa-edit"></i></button></a>
                                </td>
                                <td class="fit">
                                    <a href="{% url 'reports:delete-view' pk=obj.id %}"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
$(".open-modal").on("click", function() {
    const r_id = $(this).attr("data-url")
    $("#report_id").val(r_id)
    console.log(r_id)
});

</script>

{% endblock content %}

reports/templates/reports/select.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}select a day{% endblock title %}


{% block content %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(function(){
    $(".datepicker").datepicker({'dateFormat': 'yy-mm-dd'}).val()
});
</script>
 
<div class="col-6 mx-auto">
    <div class="text-white text-center h3 m-5">Select a line and a day </div>
    <form action="" method="POST" class="form-control" autocomplete="off">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>



{% endblock content %}

reports/templates/reports/summary.html
{% extends 'base.html' %}
{% load oknok %}
{% load substract %}

{% block title %}<a href="/">Home</a>{% endblock title %}

{% block content %}



<div class="container bg-white py-2 rounded">
    <div class="col-12">
        <div class="text-muted h2">
            <i class="fas fa-tachometer-alt mr-3"></i>Results
        </div>
    </div>
    <div class="col">
        Summary of: <strong>{{ day }} - {{ line }}</strong>
    </div>
    <br>
    <table class="table table-sm text-center">
        <thead>
            <tr>
                <th scope="col">Plan</th>
                <th scope="col">Execution</th>
                <th scope="col">Difference</th>
                <th scope="col">OK?</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ plan }}</td>
                <td>{{ execution }}</td>
                <td>{{ execution|substract:plan }}</td>
                <td>{{ execution|oknok:plan }}</td>
            </tr>
        </tbody>
    </table>
    <br>
    <h3>Problems</h3>
    <hr>
    {% for problem in problems_reported %}
    <small class="text-muted">{{ problem.problem_id }}</small><br>
    {{ problem.category }}<br>
    {{ problem.description }}<br>
    {{ problem.breakdown}} min<br>
    <hr>
    {% endfor %}
</div>

{% endblock content %}

reports/templates/reports/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}update{% endblock title %}

{% block content %}

<div class="col-9 mx-auto">
    <div class="card p-4">
        <div class="text-muted mb-2 h4"> Production Line: {{ object.production_line }} </div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>


{% endblock content %}