improveo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import PostCreateView, like_post, GeneralDetailPost, ProblemDetailPost, GeneralPostDelete

app_name = 'posts'

urlpatterns = [
    path('', PostCreateView.as_view(), name="post-list"),
    path('like/', like_post, name="post-like"),
    path('<pk>/detail/', GeneralDetailPost.as_view(), name='gp-detail'),
    path('<pk1>/<pk>/detail/', ProblemDetailPost.as_view(), name="pp-detail"),
    path('<pk>/delete/', GeneralPostDelete.as_view(), name="gp-delete"),
]

profiles/urls.py
from django.urls import path
from django.conf.urls import url
from .views import profile_view
from . import views
app_name = 'profiles'

urlpatterns = [
    path('', profile_view, name='profile-view'),
    path('panel/', views.panel, name='panel'),
    path('prices/', views.prices, name='prices'),
    path('stock/', views.stock, name='stock'),
    # path('sleep/', test_view_1, name='test-view-1'),
    # path('view3/', test_view_2, name='test-view-2'),
]

reports/urls.py
from django.urls import path
from .views import (
    report_view, delete_view, ReportUpdateView, HomeView, SelectView, main_report_summary, get_generated_problems_in_pdf
)

app_name = 'reports'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('reports/', SelectView.as_view(), name="select-view"),
    path('reports/summary/', main_report_summary, name="summary-view"),
    path('reports/<str:production_line>/<pk>/update/',
         ReportUpdateView.as_view(), name="update-view"),
    path('reports/<str:production_line>/', report_view, name="report-view"),
    path('reports/delete/<pk>/', delete_view, name='delete-view'),
    path('reports/generate/pdf/', get_generated_problems_in_pdf, name='pdf'),
]

# /{{obj.production_line}}/{{obj.pk}}/update/

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <title>MutationCode {% block title %}{% endblock title %}</title>
    <!--custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!--Fontawesome-->
	    <script src="https://kit.fontawesome.com/6809eb288c.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
  </head>

 
  <body>


{% include 'navbar.html' %}
    <section class="bg-dark" style="min-height:85vh">
        <div class="pt-big">

        {% block content %}
        {% endblock content %}
    	</div>
		</section>		
	        <!-- Scroll Top Button -->

    {% include 'footer.html' %}


		   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer>
    <div class="col-12">
        <div class="row">
            <div class="col-8 p-5">
              <img src="{%static 'images/logo/logo.png' %}" class="brand-image" alt="logo">
            </div>

            <div class="col-4 p-5">
                <div class="container h1 text-right">
                    <i class="fab fa-facebook-f ml-2"></i>
                    <i class="fab fa-instagram ml-2"></i>
                    <i class="fab fa-twitter ml-2"></i>
                    <i class="fab fa-youtube ml-2"></i>

                </div>
             
   
              
            </div>
        </div>
    </div>
    <div class="col-12 bg-white text-center p-2"><p>&copy; 2020 MutationCode<p></div>
</footer>


 <!--- pk_2462f6f6db344a55b0a7cdc46b090cef    ->

templates/navbar.html
{% load static %}
{% url 'profiles:profile-view' as path_profiles %}
{% url 'reports:home' as path_home %}
{% url 'posts:post-list' as path_board %}
{% url 'reports:select-view' as path_report %}




	
<nav class="navbar navbar-icon-top navbar-expand navbar-dark bg-dark border-bottom border-secondary font-q fixed-top py-3">

        <div class="container">

            <ul class="navbar-nav mr-auto">
             {% if request.user.is_authenticated %}
                <li class="nav-item {% if request.path == path_home %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:home' %}"><img src="{%static 'images/logo/logo.png' %}" class="brand-image" alt="logo" style="height:4rem"></a>
                </li>

                <li class="nav-item {% if request.path == path_report %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:select-view' %}"><img src="{%static 'images/report.png' %}" class="img-avatar brand-image" alt="profile picture" style="height:3rem"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:pdf' %}"><img src="{%static 'images/pdf.png' %}" class="img-avatar brand-image" alt="profile picture" style="height:3rem"></a>
                </li>
                 <li class="nav-item {% if request.path == path_board %}active{% endif %}">
                    <a class="nav-link" href="{% url 'posts:post-list' %}"><img src="{%static 'images/mic.png' %}" class="img-avatar brand-image" alt="profile picture" style="height:3rem"></a>
                </li>    
                   {% else %}

                 <li class="nav-item {% if request.path == path_home %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:home' %}"><img src="{%static 'images/logo/logo.png' %}" class="brand-image" alt="logo" style="height:2.6rem"></a>
                </li>

                 {% endif %}
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                    <a class="btn" href="{% url 'profiles:panel' %}"><img src="{%static 'images/crypto.png' %}" class="img-avatar brand-image" alt="profile picture" style="height:3.5rem;width:3.5rem"></a>
                    </li>

                    <li class="nav-item {% if request.path == path_profiles %}active{% endif %}">
                        <a href="{% url 'profiles:profile-view' %}" class="nav-link">
                            <img src="{{ picture.url }}" class="img-avatar brand-image img-circle" alt="profile picture">
                            <span class="ml-2">{{request.user}}</span>
                        </a>
                    </li>
                  
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">
                            <i class="fas fa-power-off mt-2"></i>
                        </a>
                    </li>

                {% else %}
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">
                            <i class="fa fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
            </div>
            
					</nav> <!-- /.theme-feature-menu -->



<!-- 

   <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="nav-item {% if request.path == path_home %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:home' %}">Home</a>
                </li>
                <li class="nav-item {% if request.path == path_board %}active{% endif %}">
                    <a class="nav-link" href="{% url 'posts:post-list' %}">Board</a>
                </li>
                <li class="nav-item {% if request.path == path_report %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:select-view' %}">Get report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:pdf' %}">Todays PDF</a>
                </li>        
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == path_profiles %}active{% endif %}">
                        <a href="{% url 'profiles:profile-view' %}" class="nav-link">
                            <img src="{{ picture.url }}" class="img-avatar" alt="profile picture">
                            <span class="ml-2">{{request.user}}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">
                            <i class="fas fa-power-off mt-2"></i>
                        </a>
                    </li>
                {% else %}
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">
                            <i class="fa fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
	   </div>
</nav>


-->