improveo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import PostCreateView, like_post, GeneralDetailPost, ProblemDetailPost, GeneralPostDelete

app_name = 'posts'

urlpatterns = [
    path('', PostCreateView.as_view(), name="post-list"),
    path('like/', like_post, name="post-like"),
    path('<pk>/detail/', GeneralDetailPost.as_view(), name='gp-detail'),
    path('<pk1>/<pk>/detail/', ProblemDetailPost.as_view(), name="pp-detail"),
    path('<pk>/delete/', GeneralPostDelete.as_view(), name="gp-delete"),
]

posts/models.py
from django.db import models
from profiles.models import Profile
from reports.models import Report, ProblemReported
from django.core.validators import FileExtensionValidator
from django.urls import reverse
import uuid
import os
# Create your models here.

LIKE_CHOICES = (
    ("Like", "Like"),
    ("Unlike", "Unlike"),
)


class PostManager(models.Manager):
    def public_only(self):
        return self.filter(problem_reported__public=True)


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    liked = models.ManyToManyField(Profile, related_name="liked", blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def num_likes(self):
        return self.liked.all().count()


class ProblemPost(Post):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    problem_reported = models.ForeignKey(
        ProblemReported, on_delete=models.CASCADE)

    objects = PostManager()

    def __str__(self):
        return "{}".format(self.problem_reported.description[:50])

    def get_absolute_url(self):
        return reverse("posts:pp-detail", kwargs={"pk1": self.pk, 'pk': self.problem_reported.id})


def get_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "{}.{}".format(uuid.uuid4(), ext)
    return os.path.join('uploads/posts/img', filename)


'''
1. specify the path static_cdn -> media_root -> uploads -> images
2. picture1.png -> 59afab01-6482-4f18-9527-f60e18def5fa.png
'''


class GeneralPost(Post):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=360)
    image = models.ImageField(upload_to=get_upload_path, blank=True, validators=[
                              FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("posts:gp-detail", kwargs={"pk": self.pk})


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,
                             default="Like", max_length=10)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(
        GeneralPost, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(max_length=360)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.pk)

    class Meta:
        ordering = ('-created',)

posts/forms.py
from django import forms
from .models import GeneralPost, Comment
from django.core.validators import ValidationError


class PostForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = GeneralPost
        fields = ('title', 'description', 'image')

    def clean_description(self):
        desc = self.cleaned_data.get('description')
        if len(desc) < 10:
            raise ValidationError("Description too short")
        return desc

class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 4, 'placeholder': 'your comment here...'}))

    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DeleteView, DetailView
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from .models import ProblemPost, GeneralPost
from itertools import chain
from profiles.models import Profile
from posts.models import Post, Like
from .mixins import FormUserRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
# Create your views here.


class GeneralPostDelete(LoginRequiredMixin, DeleteView):
    model = GeneralPost
    template_name = 'posts/confirm.html'
    success_url = reverse_lazy('posts:post-list')

    def get_object(self, *args, **kwargs):
        obj = super(GeneralPostDelete, self).get_object()
        if not obj.author.user == self.request.user:
            raise ValueError("You have to be the owner of this post to delete it")
        return obj


class ProblemDetailPost(LoginRequiredMixin, DetailView):
    model = ProblemPost
    template_name = 'posts/detail.html'
    pk_url_kwarg = 'pk1'
    # context_object_name = 'voldemort'


class GeneralDetailPost(LoginRequiredMixin, DetailView):
    model = GeneralPost
    template_name = 'posts/detail.html'
    # context_object_name = 'voldemort'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        post_ = get_object_or_404(GeneralPost, pk=pk)
        return post_

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context

    def post(self, *args, **kwargs):
        post_ = self.get_object()
        form = CommentForm(self.request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            profile = Profile.objects.get(user=self.request.user)
            instance.user = profile
            instance.post = post_
            instance.body = form.cleaned_data.get('body')
            form.save()
        return redirect(self.request.META.get('HTTP_REFERER'))


class PostCreateView(FormUserRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'posts/board.html'
    success_url = reverse_lazy('posts:post-list')

    def get_context_data(self, **kwargs):
        qs1 = ProblemPost.objects.public_only()
        qs2 = GeneralPost.objects.all()
        qs = sorted(chain(qs1, qs2), reverse=True, key=lambda obj: obj.created)
        context = super().get_context_data(**kwargs)
        context["object_list"] = qs
        return context


def like_post(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

    like, created = Like.objects.get_or_create(user=profile, post_id=post_id)
    if not created:
        if like.value == "Like":
            like.value = "Unlike"
        else:
            like.value = "Like"
    like.save()
    return redirect('posts:post-list')

posts/templates/posts/board.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!---
{% block title %}<a href="/"> Home</a>{% endblock title %}
-->
{% block content %}






<div class="col-8 mx-auto">
<div class="container bg-white pt-2 pb-4 rounded">
    <form action="" method="POST" class="form-control" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>



<br>
{% for obj in object_list %}
{% if obj.problem_reported %}
    <div class="card card-body mt-3 border border-primary">
    <small class="text-muted">author: {{ obj.problem_reported.user}} | {{obj.problem_reported.created|timesince}} ago </small>
    <hr>
    <h5 class="card-title">{{ obj.problem_reported.category}}</h5>
    <p class="card-text">{{ obj.problem_reported.description}}</p>
{% else %}
    <div class="card card-body mt-3 border border-danger">
    {% if obj.image %}
        <div class="mb-3"><img class="w-100" src="{{ obj.image.url }}"></div>
    {% endif %}
    <small class="text-muted">author: {{ obj.author}} | {{obj.created|timesince}} ago </small>
    <hr>
    <h5 class="card-title">{{ obj.title}}</h5>
    <p class="card-text">{{ obj.description}}</p>
{% endif %}
<form action="{% url 'posts:post-like' %}" method="POST">
{% csrf_token %}
<input type="hidden" name="post_id" value="{{ obj.id }}">
<div class="row">
<div class="col-4">
<button class="btn btn-link" type="submit" style="text-decoration:none">

{% if profile not in obj.liked.all %}
<i class="far fa-thumbs-up"></i>
<span class="ml-2">Like</span></button>
{% else %}
<i class="far fa-thumbs-down"></i>
<span class="ml-2">Unlike</span></button>
{% endif %}

</button>
<span>{{ obj.liked.all.count }} likes</span>
</div>
</form>
<div class="col-3">
<a href="{{ obj.get_absolute_url }}" class="btn btn-primary"><span class="ml-2"><i class="fas fa-search mr-2"></i>details</span></a>
</div>
</div>


</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>


{% endfor %}
</div>
{% endblock content %}

posts/templates/posts/confirm.html
{% extends 'base.html' %}
{% block title %}delete this post?{% endblock title %}

{% block content %}


<div class='col-9 mx-auto'>
    <div class='card p-4'>
        <form method="POST">
        {% csrf_token %}
            <p>Are you you want to delete this "{{ object }}"?</p>
            <button type="submit" class="btn btn-primary">Confirm delete</button>
        </form>
    </div>
</div>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} post details{% endblock title %}

{% block content %}



<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-ve35{border-color:#c0c0c0;text-align:left;vertical-align:middle}
.tg .tg-wo29{border-color:#c0c0c0;text-align:left;vertical-align:top}

.show {
    display: none;
}

#comments{
    cursor: pointer
}
</style>

<script>
$(document).ready(function(){
    $('#comments').click(function(){
        $('#comment-box').toggleClass('show');
    })
})
</script>

<div class="col-9 mx-auto">
<div class="bg-white p-4 rounded">

{% if object.report %}
    <table class="tg">
    <tr>
        <th class="tg-ve35">Author</th>
        <th class="tg-wo29">{{ object.author }}</th>
    </tr>
    <tr>
        <td class="tg-wo29">Day</td>
        <td class="tg-wo29">{{ object.report.day }}</td>
    </tr>
    <tr>
        <td class="tg-wo29">Hour from</td>
        <td class="tg-wo29">{{ object.report.start_hour }}</td>
    </tr>
    <tr>
        <td class="tg-wo29">Hour to</td>
        <td class="tg-wo29">{{ object.report.end_hour }}</td>
    </tr>
        <tr>
        <td class="tg-wo29">Product / Production Line</td>
        <td class="tg-wo29">{{ object.report.product }} / {{ object.report.production_line }}</td>
    </tr>
        <tr>
        <td class="tg-wo29">Plan / Execution</td>
        <td class="tg-wo29">{{ object.report.plan }} / {{ object.report.execution }}</td>
    </tr>
    </table>
    <br>
    <strong>{{ object.problem_reported.category }}</strong>
    <br>
    <small class="text-muted">{{object.problem_reported.problem_id }}</small>
    <br>
    Cost: {{object.problem_reported.breakdown }} min

{% else %}
    {% if object.image %}
        <div class="mb-3"><Img class="w-100" src="{{object.image.url}}"></div>
    {% endif %}
    <h5>{{object.title}}</h5>
    <p>{{object.description}}</p>
{% endif %}

<div class="row">
    <div class="col-2 my-3">
        <a href="{% url 'posts:post-list' %}">
            <button class="btn btn-warning">
            <i class="fas fa-arrow-left mr-2"></i> Back to board
            </button>
        </a>
    </div>
    {% if not object.report and object.author.user == request.user %}
        <div class="col-2 my-3">
            <a href="{% url 'posts:gp-delete' object.pk %}">
                <button class="btn btn-danger ml-2">
                    <i class="fas fa-times"></i>
                </button>
            </a>
        </div>
    {% endif %}
</div>
{% if not object.report %}

<h3>Share your thoughts</h3>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Add comment</button>
</form>
<div id="comments">All comments ({{object.comments.all.count}})</div>
<br>
<div id="comment-box" class='show'>
{% if object.comments.all %}
    {% for c in object.comments.all %}
        <div class="card p-3 my-2">
            <div class="row">
                <div class='col-2'>
                    <img src="{{ c.user.profile_picture.url }}" width="60" height="60" class="rounded-circle border">
                </div>
                <div class='col-8'>
                    <div class = 'text muted small mb-1'> {{c.user}} | {{ c.created|timesince }} ago </div>
                    <div>{{ c.body }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
<h3>No comments yet</h3>
{% endif %}
</div>


{% endif %}

</div>
</div>

{% endblock content %}